### ISSUE TITLE
-n switch doesn't work?

### ISSUE THREAD

**Issue by fuzzy76** [bobthecow/coda-cli#3]
I can't get -n or --new-window to work at all.

**Comment by fuzzy76** [comment]
Actually --ls-tabs doesn't work either. It looks like your method for checking if Coda is running thinks it isn't (I must confess I have no idea what coda_is_running() does)...

**Comment by fuzzy76** [comment]
Your code works :) It's just that osascript outputs some error messages on my system:

fuzzy76@hpmbp:~$ osascript -e 'tell application "System Events" to (count (every process whose creator type is "TStu")) as boolean'
2011-10-18 12:20:52.398 osascript[3165:707] Error loading /Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types:  dlopen(/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types, 262): no suitable image found.  Did find:
    /Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types: no matching architecture in universal wrapper
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" declares no loadable handlers.
true

I'll fix Adobes brokenness locally for now. :)

**Comment by bobthecow** [comment]
Actually, I might have a fix for that. Reopening :)

**Comment by bobthecow** [comment]
Can you do me a favor and [try this version](https://raw.github.com/bobthecow/coda-cli/develop/coda) with your broken Adobe osax? The fix works for me locally.

Thanks.

**Comment by fuzzy76** [comment]
That worked! :)

Luckily the old Adobe osax was still in my trash

On Tue, Oct 18, 2011 at 13:44, Justin Hileman
reply@reply.github.com
wrote:

**Comment by bobthecow** [comment]
Great! Thanks for your help.
