### ISSUE TITLE
coda -w not waiting

### ISSUE THREAD

**Issue by livkiss** [bobthecow/coda-cli#7]
I did configure 'coda -w' as my EDITOR in .profile and checked with 'echo $EDITOR'.
Now if I git commit (or manually coda -w somefile) it does not work (i.e. coda opens, but Terminal is not waiting).

I installed coda 1.0.3 via brew

**Comment by bobthecow** [comment]
Thanks for the heads up. This is fixed in c8e973dfe5191b52d991dbeea4ba2b231a86e35b

If you want to install via homebrew, go give https://github.com/mxcl/homebrew/pull/12430 a :+1: :)

**Comment by livkiss** [comment]
Now, if I "git commit" it opens Coda 2 with the COMMIT_EDITMSG open, but about 2 seconds later, Coda (1.7.5) is also launched in the background.
I can type a commit message, but another couple of seconds later, "git commit" ends with "Aborting commit due to empty commit message."

**Comment by bobthecow** [comment]
I think I've got a fix for this, but I don't have a computer with Coda 1 handy... Do me a favor and test the develop branch before I cut a new release?

https://github.com/bobthecow/coda-cli/tree/develop

**Comment by livkiss** [comment]
Not right just yet, but at least it won't open Coda 1 anymore.

When the file opens, it waits approximately 5 seconds, but after that it is over.
If I 'git commit' it still says 'Aborting commit due to empty commit message.' after that 5 seconds, but when I'm fast enough, and write and save the message file before that time frame, it works.

**Comment by bobthecow** [comment]
Try develop one more time? Should be fixed now.

**Comment by livkiss** [comment]
Now it works like a charm,

thanks

**Comment by bobthecow** [comment]
@birnenjoe Thanks for your help. These fixes have been released in v1.0.5, and they'll be in homebrew soon.
