### ISSUE TITLE
Add Coda project

### ISSUE THREAD

**Issue by atimmer** [bobthecow/coda-cli#8]
This is a feature idea.

It would be great if you could add project to coda using the command line. An example of this functionality can ben found in git tower, by using "gittower add ." you can add the current directory as a project in git tower.

**Comment by bobthecow** [comment]
It would be great... Unfortunately, Coda doesn't expose that functionality to the scripting bridge, so there's really no good way to do it with coda-cli.

**Comment by atimmer** [comment]
Thank you for looking into this.

**Comment by bobthecow** [comment]
No problem. I wish I could give you a better answer :)
